### ISSUE TITLE
Node Reaper - Add Support To Skip Nodes

### ISSUE THREAD

**Issue by mikenau** [keikoproj/governor#30]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:
We need the ability to conditionally skip reaping flappy nodes based on an instance group. We have one instance group where we expect nodes to flap between `Ready` and `NotReady` and we want to disable the node-reaper from reaping this nodes. The flapping stems from IOPS exhaustion on these nodes and we explicitly decided to not add additional IOPs capacity to save $$$$. We need the ability to disable reaping flappy nodes in this one instance group, but continue to have it enabled for our other instance groups. 

**What you expected to happen**:
The node-reaper ignores flappy nodes within one specific instance group but continues to act on flappy nodes in all other instance groups. 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:
N/A

- Kubernetes version:
`1.15.6`

```bash
→ kubectl version -o yaml
clientVersion:
  buildDate: "2020-02-13T18:06:54Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.8
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-13T11:11:50Z"
  compiler: gc
  gitCommit: 7015f71e75f670eb9e7ebd4b5749639d42e20079
  gitTreeState: clean
  gitVersion: v1.15.6
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
N/A

**Comment by mikenau** [comment]
A potential option would be to add a `governor.keikoproj.io/node-reaper-ignore-flappy` (or something similar) annotation to each node we want to disable reaping of flappy nodes. If the node-reaper sees this annotation on a flappy node it short-circuits and does not terminate it. 

This assumes there is a mechanism in place to add node annotations on a per instance group basis.

**Comment by eytan-avisror** [comment]
Annotating per node makes sense to me from the controller perspective, however it makes it a bit difficult for the user, as it would mean you would have to add this annotation on node startup via bootstrap arguments (potentially); on the other hand, not sure if there is a better way to design this if not a node annotation\label. 
WDYT?

we will need the following controls:
```
"governor.keikoproj.io/node-reaper-disabled" = "true" or "false"
"governor.keikoproj.io/reap-unready-disabled" = "true" or "false"
"governor.keikoproj.io/reap-unknown-disabled" = "true" or "false"
"governor.keikoproj.io/reap-flappy-disabled" = "true" or "false"
"governor.keikoproj.io/reap-old-disabled" = "true" or "false"
```

**Comment by mikenau** [comment]
We're on the same page. Annotating the nodes is the cleanest option from the node-reaper perspective. I'm not sure what options we have to control annotations at the node level though. It looks like this feature was requested for kops (https://github.com/kubernetes/kops/issues/3344), but didn't get much traction. I'm not sure if other k8s deployment tools have this capability.

**Comment by eytan-avisror** [comment]
@mikenau 
Pretty sure it’s possible in kops as well, but It’s simpler on EKS (bootstrap args), so I think we can definitely add this feature. 
But instead of annotations we should use labels, that way it can be passed in via —node-labels flag

**Comment by eytan-avisror** [comment]
https://github.com/kubernetes/kops/blob/master/docs/labels.md

**Comment by eytan-avisror** [comment]
Please refer to #29 when implementing.
We already cache the nodes, we just need a label check before marking reapable.

**Comment by mikenau** [comment]
@eytan-avisror - I think my post/edit came in after your initial replies. 

> We're on the same page. Annotating the nodes is the cleanest option from the node-reaper perspective. I'm not sure what options we have to control annotations at the node level though. It looks like this feature was requested for kops ([kubernetes/kops#3344](https://github.com/kubernetes/kops/issues/3344)), but didn't get much traction. I'm not sure if other k8s deployment tools have this capability.
> 
> Labels might be a better option. It looks like kops supports customizing labels on a per instance group basis - https://github.com/kubernetes/kops/blob/master/docs/labels.md. In our cluster, each instance group already has distinct labels. What if we flipped things around and added a new argument to the node-reaper allowing you to set a list of node labels to skip. Something like
> 
> ```
> --reap-flappy-node-labels-to-skip=xxxxx,yyyyy
> --reap-old-node-labels-to-skip=xxxxx,yyyyy
> --reap-unknown-node-labels-to-skip=xxxxx,yyyyy
> --reap-unready-node-labels-to-skip=xxxxx,yyyyy
> ```

What are you thoughts on flipping this around and leveraging node labels that likely already exist on an per instance group basis?

**Comment by eytan-avisror** [comment]
Why do we need to add flags in this case? It’s better if we have opt-out labels which are hard coded constants in the code, and their presence indicates a “skip” functionality.
There are a lot of flags for node reaper already so let’s try to avoid adding more.
Since labels is easier to add as kubelet args I feel good about using it for this purpose.

**Comment by mikenau** [comment]
The thought process behind the additional flags was to make this functionality immediately available without users having to add additional node labels. I agree using opt-out labels is cleaner from the node-reaper perspective.

**Comment by eytan-avisror** [comment]
Thanks @mikenau 
I think it’s reasonable to use labels as both eks and kops support adding labels on node startup. You’re right though that it means a node rotation when you add the label (or first labeling will be manual), but I think that’s a good compromise to adding more flags.

**Comment by mikenau** [comment]
Are you good using these as the new labels?
```
"governor.keikoproj.io/node-reaper-disabled" = "true" or "false"
"governor.keikoproj.io/reap-unready-disabled" = "true" or "false"
"governor.keikoproj.io/reap-unknown-disabled" = "true" or "false"
"governor.keikoproj.io/reap-flappy-disabled" = "true" or "false"
"governor.keikoproj.io/reap-old-disabled" = "true" or "false"
```

**Comment by eytan-avisror** [comment]
Yes, the existence if these label should skip reaping for the respective feature.

**Comment by pyieh** [comment]
@mikenau @eytan-avisror So the design is to use `node-reaper-disabled` for overall disabling of the node reaper, and the other labels for the individual types of reapable nodes?

**Comment by eytan-avisror** [comment]
`node-reaper-disabled` will disable all types of reaping for a given node, other label will disable specific features

**Comment by pyieh** [comment]
@eytan-avisror @mikenau 
PR has been created here:
https://github.com/keikoproj/governor/pull/31

Having trouble signing the CLA though. I think it's cause the 2 commits didn't have my Github account associated to it.
