### ISSUE TITLE
Corporate or individual CLA is required for keikoproj / governor?

### ISSUE THREAD

**Issue by rzheleva** [keikoproj/governor#43]
Hi Team, 

Apologies for not using the issue template, but it is not exactly applicable to my question 😄  

I am managing the CLAs for the company I am working for and we have an employee that wants to contribute to the keikoproj
/governor project. 

From what we have found it looks like that to contribute to the project, a contributor is required and prompted to sign an Individual CLA- https://cla-assistant.io/keikoproj/governor. However, on the keiko/community (https://github.com/keikoproj/keiko/tree/master/community) page, a corporate CLA is available, and we were wondering if we may sign that instead of the ICLA. 

May you please advise if the Keiko corporate CLA is a viable option for us to sign? And if the answer is "Yes", please advise if there are any specifics steps, apart from sending the signed CLA to Ms. Mukulika Kapas (mukulika_kapas@intuit.com), that we will need to complete so we may accept our employees PRs?

Thanks, 
Radi

**Comment by edlee2121** [comment]
Hi Radi, welcome to the community!

We will be moving from CLA to DCO in the next week.
If you cannot wait, then yes, just sign the Corporate CLA and email it to Mukulika.
FYI, our CLA bot will also ask the contributor to sign an Individual CLA.

**Comment by rzheleva** [comment]
Thank you, Ed!
