### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by hlascelles** [keikoproj/governor#50]
#### Request / Offer

This tool looks great for us. Is there a helm chart (maybe in a private repo?). If so can it be made public, and if not would you like one?

**Comment by eytan-avisror** [comment]
Hey @hlascelles,
You can find deployment examples here: https://github.com/keikoproj/governor/tree/master/examples

The deployment of governor tools as a cronjob is really quite simple, personally we do not use helm, but if you feel a helm chart will help you / others, we are happy to accept a PR with a helm chart. You can probably add a `examples/deploy` folder  with the chart.
